PKGROOT		= /opt/openvswitch
NAME        = openvswitch
VERSION     = 2.7.2
PATCHFILE   = $(NAME)-$(VERSION)-patch
DISTVERSION = $(VERSION)
RELEASE 	= 1
TARBALL_POSTFIX	= tar.gz
OVS.RPMBUILD	= $(REDHAT.SOURCES)/..
OVS.SOURCES 	= $(OVS.RPMBUILD)/SOURCES
OVS.RPMS	= $(OVS.RPMBUILD)/RPMS
OVS.SPECS	= $(OVS.RPMBUILD)/SPECS
MAKE.iscontrib	= true

